# Generated by Django 4.1.7 on 2023-02-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='bookimage',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
